package ru.kassatka.comepay_sdk.sql.tables_enums;

public enum CheckPositionModelField {
  _id,
  CHECK_ID,
  PRODUCT_EXT_ID,
  PRODUCT_NAME,
  CATEGORY_EXT_ID,
  PRODUCT_PRICE,
  COUNT,
  POSITION_PRICE_WITHOUT_DISCOUNT,
  POSITION_PRICE,
  VAT_TYPE,
  VAT_SUM,
  DISCOUNT_EXT_ID,
  DISCOUNT_NAME,
  DISCOUNT_TYPE,
  AGENT_TYPE,
  PAY_ATTRIBUTES_TYPE,
  GOOD_ATTRIBUTES_TYPE,
  DISCOUNT_VALUE,
  EGAIS_CODE,
  BAR_CODE,
  PRODUCT_TYPE,
  ALCOHOL_BY_VOLUME,
  ALCOHOL_PRODUCT_KIND_CODE,
  TARE_VOLUME,
  ALL
}
